### ISSUE TITLE
Feature Request: Add "patch-remove" command

### ISSUE THREAD

**Issue by hudri** [szeidler/composer-patches-cli#11]
I'd suggest to add a "patch-remove" command.  The syntax should be similar to the patch-add command, except you don't need the URL for non-interactive mode:

`composer patch-remove <package> <description>`

**Use case:**
I'm currently maintaining ~ 30 quite similar projects and need to perform automatic updates. I need to add a patch for a feature not yet commited to the package.
```
composer update drupal/* --with-dependencies
composer patch-add drupal/paragraphs "Issue 2907094 - Patch 7 - Paragraphs 1.8 does not work with Field Group 3.x-RC1": "https://www.drupal.org/files/issues/2907094_7_field_group_support.patch"
```

A few month later that patch was commited and that patch is no longer needed and does no longer apply. I'd need to create a script to to remove the patch from all projects, e.g. somehting like
```
composer patch-remove drupal/paragraphs "Issue 2907094 - Patch 7 - Paragraphs 1.8 does not work with Field Group 3.x-RC1"
composer require drupal/paragraphs:^1.9
```

**Comment by szeidler** [comment]
Thanks for the input @hudri . Good to see, that you use the feature in a automating context, like we do.

I just created a pull request for providing the feature.

**Comment by szeidler** [comment]
This is part of the recent release now. Thanks for your contribution.
