### ISSUE TITLE
Problems while changing the working dir

### ISSUE THREAD

**Issue by rutiolma** [szeidler/composer-patches-cli#19]
I have some problems when I add composer-patches-cli to any of my projects. It seems that my project loses its paths and files cannot be found by composer anymore.

I did some debugging and I noticed that the problem is with the code at PatchBaseCommand.php. I also noticed that PatchBaseCommand changes the working directory but this code is redundant cause it is present in Composer since version 1.5.0. See https://github.com/composer/composer/blob/1.5.0/src/Composer/Console/Application.php

I'm using Composer 1.10.7 and I tried to include composer-patches-cli on Drupal projects.
My suggestion is to remove the code introduced by PatchBaseCommand::changeWorkingDirToComposerRoot(), which fixes the issue while the functionality is still being provided by Composer.

**Comment by szeidler** [comment]
Hi,

thanks for you input. I finally committed the changes. The basecommand has changed quite a bit, so that we needed to keep the class.
