### ISSUE TITLE
The helper "dialog" is not defined.  

### ISSUE THREAD

**Issue by luksak** [szeidler/composer-patches-cli#25]
When running `composer patch-add` or `composer patch-remove`, i get the following error:

```
$ composer patch-remove drupal/core "Patch title" 
               
The helper "dialog" is not defined.                               

patch-remove <package> <description>
```

I am running on Fedora with Composer 2.0.12

**Comment by esolitos** [comment]
Hello @luksak, can you give us some info about the project where you are using this plugin?
If there is a public repo or if you can provide us a `composer.json` would be greatly appreciated and it would help us figure out what is the source of your issue.

**Comment by luksak** [comment]
Does this depend on the project I am running this on? I am running Drupal 8 and Drupal 9. Other than that I haven't install Symphony globally.

We should be using anyhow: and this is a minimal change:

https://symfony.com/doc/2.8/components/console/helpers/questionhelper.html

**Comment by luksak** [comment]
Ok, got it working!

**Comment by szeidler** [comment]
Thanks for the contribution. The PR worked like charm - I just merged it in and tagged a new release.
