### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by JPustkuchen** [szeidler/composer-patches-cli#27]
Thank a lot for this GREAT plugin, this is really really cool and I ❤️ it!!

Since switching to PHP 8 composer complains:
> szeidler/composer-patches-cli[1.0.1, ..., 1.0.4] require php ^7.0 -> your php version (8.0.10; overridden via config.platform, same as actual) does not satisfy that requirement.

Is this plugin PHP 8 checked already and requires just a change in composer.json? Or are there larger steps to take?

**Comment by szeidler** [comment]
Thanks for the contribution. I merged it in and tagged a new release to not unnecessarily block PHP 8 support.
